name: datenverbrauch
version: 0.2.8-SNAPSHOT
description: query data usage from alditalk-kundenbetreuung.de
github: section77/datenverbrauch
license: MIT
author: j-keck <jhyphenkeck@gmail.com>

ghc-options: -Wall -optl-static -optl-pthread
default-extensions: NoImplicitPrelude


executables:
  datenverbrauch:
    main: Main.hs
    source-dirs: src
    dependencies:
      - base >= 4.7 && < 5
      - bytestring
      - directory
      - filepath
      - formatting
      - HStringTemplate
      - lens
      - optparse-applicative
      - protolude
      - tagsoup
      - text
      - time
      - transformers
      - wreq-stringless

tests:
  doctest:
    main: doctest.hs
    source-dirs: test
    dependencies:
      - doctest
      - protolude
